hassio-addons/addon-ledfx

LICENSE.md
README.md
ledfx/.README.j2
ledfx/DOCS.md

📚 Update year in documentation

---

ledfx/Dockerfile
ledfx/build.json

Updates base image and package dependencies.
Change base image to base rather than python image.

⬆ Update base image and dependencies

---

ledfx/Dockerfile

Copy Paste is bad...
Fix local build arg

🔨 Fix local build

---

ledfx/requirements.txt
ledfx/rootfs/etc/cont-init.d/ledfx.sh
ledfx/rootfs/etc/services.d/ledfx/run

⬆ Update ledfx to v0.9.2

---

ledfx/Dockerfile

🔨 Add zlib-dev 1.2.11-r3

---

ledfx/Dockerfile
ledfx/build.json

https://github.com/hassio-addons/addon-base/releases/tag/v9.1.2

Upgrade add-on base image to 9.1.2

---

ledfx/Dockerfile

:arrow_up: Upgrades python3 to 3.8.7-r1

---

ledfx/Dockerfile

⬆️ Upgrades python3 to 3.8.8-r0

---

ledfx/Dockerfile
ledfx/build.json

⬆ Update base image to v9.1.8
⬆ Update cython to v0.29.21-r1

⬆ Update base image to v9.1.8 and dependencies

---

ledfx/Dockerfile
ledfx/build.json

Upgrades add-on base image to v9.2.0

⬆️ Upgrades add-on base image to v9.2.0

---

ledfx/Dockerfile

⬆️ Upgrades python3 to 3.8.10-r0

---

ledfx/Dockerfile
ledfx/build.json

Upgrades add-on base image to v9.2.2

⬆️ Upgrades add-on base image to v9.2.2

---

ledfx/Dockerfile
ledfx/build.json

Upgrade add-on to the latest base image.
Additionally, cleaned up some redundant dependencies, a cache folder and added some pre-build wheels from Alpine to speed things up.

⬆️ Upgrades add-on base image to v10.0.1

---

ledfx/Dockerfile

Upgrades ffmpeg-libs to 4.4.1-r0

⬆️ Upgrades ffmpeg-libs to 4.4.1-r0

---

ledfx/Dockerfile
ledfx/build.yaml

Upgrades add-on base image to 10.2.0

⬆️ Upgrades add-on base image to 10.2.0

---

ledfx/Dockerfile
ledfx/build.yaml

Upgrades add-on base image to 10.2.2

⬆️ Upgrades add-on base image to 10.2.2

---

ledfx/Dockerfile
ledfx/build.yaml

Upgrades add-on base image to 11.0.0

⬆️ Upgrades add-on base image to 11.0.0

---

ledfx/DOCS.md
ledfx/config.yaml
ledfx/rootfs/etc/cont-init.d/nginx.sh
ledfx/rootfs/etc/nginx/templates/direct.gtpl

🔨 Add leave_front_door_open option

🔨 Add leave_front_door_open option

---

LICENSE.md
README.md
ledfx/.README.j2
ledfx/DOCS.md

:fireworks: Updates maintenance/license year to 2022

---

ledfx/Dockerfile
ledfx/build.yaml

Upgrades add-on base image to 11.1.0

⬆️ Upgrades add-on base image to 11.1.0

---

ledfx/build.yaml
ledfx/config.yaml

Sign add-on with Codenotary Community Attestation Service (CAS)

:lock: Sign add-on with Codenotary Community Attestation Service (CAS)

---

ledfx/Dockerfile
ledfx/build.yaml
ledfx/config.yaml
ledfx/rootfs/etc/cont-init.d/ledfx.sh
ledfx/rootfs/etc/cont-init.d/nginx.sh
ledfx/rootfs/etc/services.d/ledfx/finish
ledfx/rootfs/etc/services.d/ledfx/run
ledfx/rootfs/etc/services.d/nginx/finish
ledfx/rootfs/etc/services.d/nginx/run

Upgrades add-on base image to 12.0.0

⬆️ Upgrades add-on base image to 12.0.0

---

ledfx/Dockerfile
ledfx/build.yaml

Upgrades add-on base image to 12.2.3

⬆️ Upgrades add-on base image to 12.2.3

---

ledfx/Dockerfile

⬆️ Upgrades nginx to 1.22.1-r0

---

ledfx/Dockerfile
ledfx/build.yaml

⬆️ Upgrades add-on base image to 13.0.0

---

.github/workflows/deploy.yaml

:ambulance: Fix missing CAS API Key in CI
